name: Build
on: 
    push: 
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 20.2.0
            - name: Build
              uses: alexthemaster/action-build-typescript@v1.3.1
              