name: Build
on: 
    push: 
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout project
              uses: actions/checkout@v3
            - name: Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 20.2.0
            - name: Build
              run: npm install && npm run build
            - name: Pack Build
              uses: dfreilich/pack-action@v2.0.0
              with:
                args: 'build hello-langchain --builder paketobuildpacks/builder:full --buildpack gcr.io/paketo-buildpacks/nodejs --env BP_NODE_OPTIMIZE_MEMORY=true' 
